version: '3.8'
services:
  app:
    volumes:
      - .:/var/www/html/
    ports:
      - 80:80
    image: uploady:latest
    restart: always
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "uploady"
      MYSQL_USER: "uploady"
      MYSQL_PASSWORD: "uploady"
      MYSQL_ROOT_PASSWORD: "uploady"
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql

volumes:
  mysql_data: