version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    image: fariscode/uploady:latest
    restart: always
    depends_on:
      - db
  
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "uploady"
      MYSQL_USER: "uploady"
      MYSQL_PASSWORD: "uploady"
      MYSQL_ROOT_PASSWORD: "uploady"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db

volumes:
  mysql_data: