services:
  app:
    ports:
      - 80:8080
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      SSL_MODE: "off"
    image: serversideup/php:8.3-fpm-apache
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "uploady"
      MYSQL_USER: "uploady"
      MYSQL_PASSWORD: "uploady"
      MYSQL_ROOT_PASSWORD: "uploady"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
